//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diffTest {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("diffTest.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Lines for context과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContextLines {
            get {
                return ResourceManager.GetString("ContextLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy this line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyThisLine {
            get {
                return ResourceManager.GetString("CopyThisLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diff과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Diff {
            get {
                return ResourceManager.GetString("Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unified view과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InlineMode {
            get {
                return ResourceManager.GetString("InlineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Same {
            get {
                return ResourceManager.GetString("Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as…과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split view과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SideBySideMode {
            get {
                return ResourceManager.GetString("SideBySideMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collapse unchanged sections과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SkipUnchangedLines {
            get {
                return ResourceManager.GetString("SkipUnchangedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SwitchViewMode {
            get {
                return ResourceManager.GetString("SwitchViewMode", resourceCulture);
            }
        }
    }
}
